### PR TITLE
Adding support for Travis CI.

### PR DESCRIPTION
**Pull request by juliancheal**
With support for Ruby 2.2, and JRuby.

Updated Readme.md with Gem version badge, and Travis build status.

### CODE REVIEW

**Comment by sidoh** [comment]
Thanks!

**Comment by juliancheal** [comment]
@sidoh I think you'll need to enable Travis CI access in the repository settings.

**Comment by sidoh** [comment]
Hmm, I thought I did. I created the webhook and enabled it within Travis. Is there something else I need to do?

**Comment by juliancheal** [comment]
@sidoh Hmn just what's on here https://docs.travis-ci.com/user/getting-started/ As the Travis page says there are no builds for this repository. 😄

**Comment by sidoh** [comment]
Haha. Right. Was thinking that was because there have been not commits since the `.travis.yml` was added.

> Travis only runs a build on the commits you push AFTER adding the repository to Travis.

**Comment by sidoh** [comment]
Think that was it. Made a whitespace change and it triggered a build :)

**Pull request merged**
